#!/bin/sh

bspc config border_width          2
bspc config top_padding           0
bspc config window_gap            5
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config auto_cancel           true
bspc config focus_follows_pointer true

# Colors
bspc config focused_border_color \#2379C2
bspc config normal_border_color none
bspc config presel_border_color none

bspc monitor -d 1 2 3 4 5 6

bspc rule -a Firefox fullscreen=on desktop='^1'

bspc rule -a Termite desktop='^2'



xsetroot -cursor_name left_ptr
xset -dpms
xset s off

feh --bg-scale ~/Изображения/123.jpg &
#~/./.reader.sh | lemonbar -f "fontawesome:size=14" -f "Cantarell:size=12" -g 1012x25+5+4 -p -u 2 &
sxhkd &
sh ~/.config/bspwm/bar.sh &
#~/./.lemon.py &
#spectrumyzer &
setxkbmap -option caps:none &
#compton &
