#! /bin/sh

# autostart
# ==============================================================================
# NOTE sxhkd and polybar are core parts of my bspwm
# the rest are loaded only if they are in the PATH

sxhkd &
. $HOME/.config/polybar/launch.sh &
emacs --daemon &

if [ -x /usr/bin/feh ]; then
    feh --bg-fill ~/.wallpaper.png
fi

if [ -x /usr/bin/compton ]; then
    compton -b &
fi

if [ -x /usr/bin/dunst ]; then
    dunst &
fi

if [ -x /usr/bin/redshift ]; then
    redshift -c ~/.config/redshift.conf &
fi

if [ -x /usr/bin/unclutter ]; then
    unclutter &
fi


if [ -x /usr/bin/xinput ]; then
    # `xinput list` devices
    # `xinput list-props` device properties

    # syntax is [id] [prop] [boolean]
    # enable touchpad tap to click
    xinput set-prop 11 277 1
    # xinput set-prop 12 295 1
fi

# Visual options
# ==============================================================================

# workspaces
# ------------------------------------------------------------------------------
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# window rules
# ------------------------------------------------------------------------------
bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer false
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
# bspc config initial_polarity second_child

# colours
# ------------------------------------------------------------------------------

# define scheme
source "$HOME/.my_Xcolors/active-tempus-theme.sh"

# window decorations
bspc config normal_border_color "$background"
bspc config active_border_color "$color8"
bspc config focused_border_color "$color10"
bspc config presel_feedback_color "$color13"
