#!/bin/sh
static=main
link=xl4j1l08.default
volatile=/dev/shm/firefox-$USER

IFS=
set -efu

cd ~/.mozilla/firefox

if [ ! -r $volatile ]; then
    mkdir -m0700 $volatile
fi

if [ "$(readlink $link)" != "$volatile" ]; then
    mv $link $static
    ln -s $volatile $link
fi

if [ -e $link/.unpacked ]; then
    rsync -av --delete --exclude .unpacked ./$link/ ./$static/
else
    rsync -av ./$static/ ./$link/
    touch $link/.unpacked
fi
